core:
  workspace_id: "00000000-0000-0000-0000-000000000000"
  repository_directory: "."
  parameter: "parameter.yml"
  item_types_in_scope:
    - Notebook
    - Lakehouse
    - SQLDatabase
    - DataPipeline
    - Environment
    - Eventhouse
    - VariableLibrary
    - UserDataFunction

publish:
  exclude_regex: "^(TEMP_|DEBUG_|DRAFT_).*"
  folder_exclude_regex: "^/(incubation|scratch|archive|temp|debug|drafts)(/|$)"
  skip: false

unpublish:
  exclude_regex: "^(SYSTEM_|ADMIN_).*"
  skip: true

features:
  - enable_shortcut_publish
  - enable_exclude_folder
  - enable_environment_variable_replacement

constants:
  DEFAULT_API_ROOT_URL: "https://api.fabric.microsoft.com"
